cc_library(
    name = "libccspec",
    srcs = glob(["src/**/*.cc"]),
    includes = ["include"],
    hdrs = glob(["include/**/*.h"]) + glob(["include/**/*.hpp"]),
    visibility = ["//visibility:public"],
    linkstatic = False
)
