#!/usr/bin/env bash

set -e -x

setup() {
  git submodule init 
  git submodule update 

  rm -rf build bin lib
  mkdir -p build
}

build() {
  cd build
  cmake ..
  make -j 16
  make install
  cd ..
}

run() {
  export LD_LIBRARY_PATH=$(pwd)/lib

  # now run the tests
  for binary in $(find bin -type f -perm -111); do 
    ${binary}
  done
}

ubuntu() {
  # remove -stdlib flag for clang compilers
  find . -name '*.txt' | xargs sed -i '' -e 's/-stdlib=libc++//g'
}

travis() {
  setup
  build
  ubuntu
  run
}

main() {
  setup
  build
  run
}


action="${1:-"main"}"

${action}
