cc_binary(
    name = "scheduler_specs",
    srcs = ["message_scheduler_spec.cc"],
    includes = ["ccspec/include"],
    visibility = ["//visibility:public"],
    deps = [
       "//src/schedule:schedule",
       "//spec/ccspec:libccspec"
   ],
)
